<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Client-Info, Apikey');
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

// Фиксированная конфигурация для Трансляции канала Розпакуй
$config = [
    'login' => 'Zaharchenko',
    'password' => 'Zaharchenko1234',
    'roleId' => '9',
    'sourceFilter' => ['Трансляция канала Розпакуй ТВ'],
    'processTimeSourceId' => '65',
];

$debug = isset($_GET['debug']) && $_GET['debug'] === 'true';

error_log("=== ROZPAKUJ API CALLED ===");
error_log("Method: " . $_SERVER['REQUEST_METHOD']);

error_log("Using config: " . json_encode($config));

// Функция логина в CRM (использует рабочую логику из test_crm_debug.php)
function loginToCRM($config) {
    $loginUrl = 'https://datapoint.center/';
    $cookieFile = sys_get_temp_dir() . '/crm_cookies_' . uniqid() . '.txt';
    
    // Шаг 1: Получаем страницу входа
    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL => $loginUrl,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_COOKIEJAR => $cookieFile,
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_HTTPHEADER => [
            'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        ],
    ]);
    
    $initialHtml = curl_exec($ch);
    $initialCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    error_log("Initial request HTTP code: $initialCode");
    
    // Шаг 2: Отправляем форму логина
    $postData = [
        'auth_login' => $config['login'],
        'auth_password' => $config['password'],
        'logok' => 'Войти',
    ];
    
    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL => $loginUrl,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => http_build_query($postData),
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_COOKIEJAR => $cookieFile,
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_HEADER => true,
        CURLOPT_HTTPHEADER => [
            'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
            'Referer: ' . $loginUrl,
            'Origin: https://datapoint.center',
        ],
    ]);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $headerSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    $headers = substr($response, 0, $headerSize);
    $body = substr($response, $headerSize);
    curl_close($ch);
    
    error_log("Login response HTTP code: $httpCode");
    
    // Извлекаем PHPSESSID из Set-Cookie
    $phpSessionId = '';
    if (preg_match('/Set-Cookie:.*?PHPSESSID=([^;]+)/i', $headers, $matches)) {
        $phpSessionId = trim($matches[1]);
        error_log("PHPSESSID found: $phpSessionId");
        
        // Обновляем cookie файл с правильным PHPSESSID
        $cookieContent = "# Netscape HTTP Cookie File\n";
        $cookieContent .= "# https://curl.se/docs/http-cookies.html\n";
        $cookieContent .= "# This file was generated by libcurl! Edit at your own risk.\n\n";
        $cookieContent .= "datapoint.center\tFALSE\t/\tFALSE\t0\tPHPSESSID\t{$phpSessionId}\n";
        file_put_contents($cookieFile, $cookieContent);
    }
    
    // Если редирект - следуем ему
    if ($httpCode === 302 || $httpCode === 303) {
        if (preg_match('/Location:\s*(.+)/i', $headers, $matches)) {
            $redirectUrl = trim($matches[1]);
            if (!preg_match('/^https?:\/\//', $redirectUrl)) {
                $redirectUrl = 'https://datapoint.center' . $redirectUrl;
            }
            error_log("Following redirect to: $redirectUrl");
            
            $ch = curl_init();
            curl_setopt_array($ch, [
                CURLOPT_URL => $redirectUrl,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_FOLLOWLOCATION => false,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_TIMEOUT => 30,
                CURLOPT_COOKIEJAR => $cookieFile,
                CURLOPT_COOKIEFILE => $cookieFile,
            ]);
            
            curl_exec($ch);
            curl_close($ch);
        }
    }
    
    // Извлекаем PHPSESSID из cookie файла
    $sessionCookie = '';
    if (file_exists($cookieFile)) {
        $cookieContent = file_get_contents($cookieFile);
        if (preg_match('/PHPSESSID\s+([^\s\n]+)/', $cookieContent, $matches)) {
            $phpSessionId = trim($matches[1]);
            $sessionCookie = 'PHPSESSID=' . $phpSessionId;
            error_log("PHPSESSID from file: $phpSessionId");
        }
    }
    
    if (empty($sessionCookie)) {
        error_log("ERROR: No PHPSESSID found");
        @unlink($cookieFile);
        return '';
    }
    
    // Проверяем авторизацию через dashboard
    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL => 'https://datapoint.center/dashboard/',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_HTTPHEADER => [
            'Cookie: ' . $sessionCookie,
            'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        ],
    ]);
    
    $verifyResponse = curl_exec($ch);
    $verifyCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    $isLoggedIn = strpos($verifyResponse, 'dashboard') !== false || 
                  strpos($verifyResponse, 'выход') !== false || 
                  strpos($verifyResponse, 'auth_login') === false;
    
    error_log("Verification code: $verifyCode, Is logged in: " . ($isLoggedIn ? 'Yes' : 'No'));
    
    if (!$isLoggedIn) {
        error_log("ERROR: Login verification failed");
        @unlink($cookieFile);
        return '';
    }
    
    // Возвращаем cookie строку и сохраняем путь к файлу для последующих запросов
    return $sessionCookie;
}

// Функция парсинга данных из HTML
function parseTableData($html) {
    $data = [
        'orders' => 0,
        'orderSum' => 0,
        'marginProfit' => 0,
        'allCalls' => 0,
        'profileCalls' => 0,
        'unprocessedCalls' => 0,
        'missedCalls' => 0,
        'missedNonTargetCalls' => 0,
        'employees' => ['total' => 0, 'work' => 0, 'pause' => 0, 'stop' => 0]
    ];
    
    // Парсим заказы
    if (preg_match('/Кол-во заказов:<\/td>\s*<td[^>]*>([^<]+)<\/td>/', $html, $matches)) {
        $data['orders'] = (int) preg_replace('/\s/', '', $matches[1]);
    }
    
    // Парсим сумму заказов
    if (preg_match('/Сумма заказов:<\/td>\s*<td[^>]*>([^<]+)<\/td>/', $html, $matches)) {
        $data['orderSum'] = (float) str_replace([',', ' '], ['.', ''], $matches[1]);
    }
    
    // Парсим прибыль
    if (preg_match('/М\. прибыль:<\/td>\s*<td[^>]*>([^<]+)<\/td>/', $html, $matches)) {
        $data['marginProfit'] = (float) str_replace([',', ' '], ['.', ''], $matches[1]);
    }
    
    // Парсим звонки
    if (preg_match('/Кол-во ВСЕХ звонков:<\/td>\s*<td[^>]*>([^<]+)<\/td>/', $html, $matches)) {
        $data['allCalls'] = (int) preg_replace('/\s/', '', $matches[1]);
    }
    
    if (preg_match('/Кол-во профильных звонков:<\/td>\s*<td[^>]*>([^<]+)<\/td>/', $html, $matches)) {
        $data['profileCalls'] = (int) preg_replace('/\s/', '', $matches[1]);
    }
    
    if (preg_match('/Кол-во НЕОБРАБОТАННЫХ звонков:<\/td>\s*<td[^>]*>([^<]+)<\/td>/', $html, $matches)) {
        $data['unprocessedCalls'] = (int) preg_replace('/\s/', '', $matches[1]);
    }
    
    if (preg_match('/Кол-во пропущенных:<\/td>\s*<td[^>]*>([^<]+)<\/td>/', $html, $matches)) {
        $data['missedCalls'] = (int) preg_replace('/\s/', '', $matches[1]);
    }
    
    if (preg_match('/Кол-во пропущенных нецелевых:<\/td>\s*<td[^>]*>([^<]+)<\/td>/', $html, $matches)) {
        $data['missedNonTargetCalls'] = (int) preg_replace('/\s/', '', $matches[1]);
    }
    
    // Парсим сотрудников
    preg_match_all('/data-type="pultstatus">Work<\/td>/', $html, $workMatches);
    preg_match_all('/data-type="pultstatus">Pause<\/td>/', $html, $pauseMatches);
    preg_match_all('/data-type="pultstatus">Stop<\/td>/', $html, $stopMatches);
    
    $data['employees']['work'] = count($workMatches[0]);
    $data['employees']['pause'] = count($pauseMatches[0]);
    $data['employees']['stop'] = count($stopMatches[0]);
    $data['employees']['total'] = $data['employees']['work'] + $data['employees']['pause'] + $data['employees']['stop'];
    
    return $data;
}

// Функция парсинга времени обработки
function parseProcessTimeData($html) {
    $groups = [
        '0–5 мин' => 0,
        '5–10 мин' => 0,
        '10–15 мин' => 0,
        '15–30 мин' => 0,
        '30–60 мин' => 0,
        '60–120 мин' => 0,
        '120+ мин' => 0
    ];
    
    error_log("parseProcessTimeData: HTML length = " . strlen($html));
    
    if (preg_match('/<table[^>]*class="[^"]*shop-table[^"]*"[^>]*>([\s\S]*?)<\/table>/i', $html, $tableMatch)) {
        error_log("parseProcessTimeData: Table found");
        $tableHtml = $tableMatch[1];
        
        if (preg_match_all('/<tr([^>]*)>([\s\S]*?)<\/tr>/i', $tableHtml, $trMatches, PREG_SET_ORDER)) {
            error_log("parseProcessTimeData: Found " . count($trMatches) . " table rows");
            foreach ($trMatches as $trMatch) {
                $trAttrs = $trMatch[1];
                $trContent = $trMatch[2];
                
                $hasOnclick = preg_match('/onclick\s*=/i', $trAttrs);
                $hasDataGroup = preg_match('/data-group\s*=/i', $trAttrs);
                
                if ($hasOnclick && !$hasDataGroup) {
                    $text = preg_replace('/<[^>]+>/', ' ', $trContent);
                    $text = preg_replace('/\s+/', ' ', trim($text));
                    
                    if (preg_match('/^(\d+)\s+\((\d+)\s+процессов\)$/', $text, $match)) {
                        $minutes = (int) $match[1];
                        $count = (int) $match[2];
                        error_log("parseProcessTimeData: Found process time - minutes: $minutes, count: $count");
                        
                        if ($minutes <= 5) $groups['0–5 мин'] += $count;
                        elseif ($minutes <= 10) $groups['5–10 мин'] += $count;
                        elseif ($minutes <= 15) $groups['10–15 мин'] += $count;
                        elseif ($minutes <= 30) $groups['15–30 мин'] += $count;
                        elseif ($minutes <= 60) $groups['30–60 мин'] += $count;
                        elseif ($minutes <= 120) $groups['60–120 мин'] += $count;
                        else $groups['120+ мин'] += $count;
                    } else {
                        error_log("parseProcessTimeData: Text doesn't match pattern: " . substr($text, 0, 100));
                    }
                }
            }
        } else {
            error_log("parseProcessTimeData: No table rows found");
        }
    } else {
        error_log("parseProcessTimeData: Table with class 'shop-table' not found");
    }
    
    $total = array_sum($groups);
    $result = [];
    foreach ($groups as $label => $count) {
        $result[] = [
            'label' => $label,
            'count' => $count,
            'percentage' => $total > 0 ? round(($count / $total) * 100, 1) : 0
        ];
    }
    
    return $result;
}

// Функция расчета процента
function calculatePercentage($value, $total) {
    if ($total == 0) return '0%';
    return round(($value / $total) * 100, 1) . '%';
}

// Функция выполнения запроса с повторными попытками
function fetchWithRetry($url, $cookies, $cookieFile, $maxRetries = 3, $isProcessTime = false) {
    for ($attempt = 1; $attempt <= $maxRetries; $attempt++) {
        $ch = curl_init();
        curl_setopt_array($ch, [
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_COOKIEFILE => $cookieFile,
            CURLOPT_COOKIEJAR => $cookieFile,
            CURLOPT_HTTPHEADER => [
                'Cookie: ' . $cookies,
                'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
                'Referer: https://datapoint.center/dashboard/',
            ],
        ]);
        
        $data = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error = curl_error($ch);
        curl_close($ch);
        
        if ($httpCode === 200 && !empty($data) && strlen($data) > 1000) {
            // Для страницы времени обработки проверяем наличие таблицы
            if ($isProcessTime) {
                if (strpos($data, 'shop-table') !== false || strpos($data, '<table') !== false) {
                    error_log("Successfully fetched process time data on attempt $attempt, length: " . strlen($data));
                    return $data;
                } else {
                    error_log("Attempt $attempt: Process time HTML doesn't contain table");
                }
            } else {
                // Для обычных страниц проверяем наличие метрик
                if (strpos($data, 'Кол-во заказов') !== false || strpos($data, 'Сумма заказов') !== false) {
                    error_log("Successfully fetched data on attempt $attempt, length: " . strlen($data));
                    return $data;
                } else {
                    error_log("Attempt $attempt: HTML doesn't contain expected data markers");
                }
            }
        } else {
            error_log("Attempt $attempt failed: HTTP code: $httpCode, Error: $error, Data length: " . strlen($data));
        }
        
        if ($attempt < $maxRetries) {
            usleep(500000); // Задержка 0.5 секунды перед повтором
        }
    }
    
    return false;
}

// Функция проверки валидности распарсенных данных
function isValidData($parsedData) {
    // Проверяем, что хотя бы одно значение не ноль (кроме missedCalls, которые могут быть 0)
    $hasData = $parsedData['orders'] > 0 || 
               $parsedData['orderSum'] > 0 || 
               $parsedData['allCalls'] > 0 ||
               $parsedData['employees']['total'] > 0;
    
    return $hasData;
}

try {
    // Логин
    $cookies = loginToCRM($config);
    
    if (empty($cookies)) {
        throw new Exception('Failed to authenticate');
    }
    
    error_log("Login successful for ROZPAKUJ, User: " . $config['login']);
    
    $today = date('Y-m-d');
    
    // Формируем URL для отфильтрованных данных
    $sourceParams = [];
    foreach ($config['sourceFilter'] as $source) {
        $sourceParams[] = 'filter_event_uservoip_que_source%5B%5D=' . urlencode($source);
    }
    $sourceParamsStr = implode('&', $sourceParams);
    
    $filteredPageUrl = "https://datapoint.center/admin/report/desiner/101/view/?filter_order_cdatetype=now&filter_order_cdateperiod=mday&filter_user_roleid%5B%5D={$config['roleId']}&filter_user_manageronline=online&{$sourceParamsStr}&filter_event_uservoip_que_sourcechild=1&templateid=&ok=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C";
    $totalPageUrl = "https://datapoint.center/admin/report/desiner/101/view/?filter_order_cdatefrom={$today}&filter_order_cdateto={$today}&filter_user_manageronline=online&filter_event_uservoip_que_sourcechild=1&templateid=&ok=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C";
    $processTimeUrl = "https://datapoint.center/admin/report/desiner/132/view/?filter_order_cdatefrom={$today}&filter_order_cdateto={$today}&filter_order_sourceid%5B%5D={$config['processTimeSourceId']}&templateid=&ok=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C";
    
    error_log("Filtered URL: $filteredPageUrl");
    error_log("Process Time URL: $processTimeUrl");
    
    // Получаем данные с повторными попытками
    $cookieFile = sys_get_temp_dir() . '/crm_cookies_' . uniqid() . '.txt';
    file_put_contents($cookieFile, "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n");
    $phpSessionId = str_replace('PHPSESSID=', '', $cookies);
    file_put_contents($cookieFile, "datapoint.center\tFALSE\t/\tFALSE\t0\tPHPSESSID\t{$phpSessionId}\n", FILE_APPEND);
    
    $maxAttempts = 3;
    $filteredData = false;
    $totalData = false;
    $processTimeData = false;
    
    for ($attempt = 1; $attempt <= $maxAttempts; $attempt++) {
        error_log("Fetch attempt $attempt of $maxAttempts");
        
        // Получаем отфильтрованные данные
        if (!$filteredData) {
            $filteredData = fetchWithRetry($filteredPageUrl, $cookies, $cookieFile, 2);
        }
        
        // Получаем общие данные
        if (!$totalData) {
            $totalData = fetchWithRetry($totalPageUrl, $cookies, $cookieFile, 2);
        }
        
        // Получаем данные о времени обработки
        if (!$processTimeData) {
            $processTimeData = fetchWithRetry($processTimeUrl, $cookies, $cookieFile, 2, true);
        }
        
        // Если все данные получены, проверяем валидность
        if ($filteredData && $totalData && $processTimeData) {
            $parsedFiltered = parseTableData($filteredData);
            $parsedTotal = parseTableData($totalData);
            
            if (isValidData($parsedFiltered) || isValidData($parsedTotal)) {
                error_log("Valid data obtained on attempt $attempt");
                break;
            } else {
                error_log("Attempt $attempt: All data is zero, retrying...");
                $filteredData = false;
                $totalData = false;
                $processTimeData = false;
                
                if ($attempt < $maxAttempts) {
                    // Перелогиниваемся перед повтором
                    error_log("Re-authenticating before retry...");
                    $cookies = loginToCRM($config);
                    if (empty($cookies)) {
                        throw new Exception('Failed to re-authenticate');
                    }
                    $phpSessionId = str_replace('PHPSESSID=', '', $cookies);
                    file_put_contents($cookieFile, "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n");
                    file_put_contents($cookieFile, "datapoint.center\tFALSE\t/\tFALSE\t0\tPHPSESSID\t{$phpSessionId}\n", FILE_APPEND);
                    sleep(1); // Задержка перед повтором
                }
            }
        } else {
            error_log("Attempt $attempt: Failed to fetch all data");
            if ($attempt < $maxAttempts) {
                sleep(1);
            }
        }
    }
    
    if (!$filteredData || !$totalData) {
        throw new Exception('Failed to fetch data after ' . $maxAttempts . ' attempts');
    }
    
    if (!$processTimeData) {
        error_log("WARNING: Failed to fetch process time data, using empty data");
        $processTimeData = '';
    }
    
    @unlink($cookieFile);
    
    if ($debug) {
        echo json_encode([
            'filteredHtml' => substr($filteredData, 0, 1000),
            'totalHtml' => substr($totalData, 0, 1000),
            'processTimeHtml' => substr($processTimeData, 0, 1000),
            'cookies' => $cookies,
            'session' => 'rozpakuj',
            'config' => $config,
        ]);
        exit;
    }
    
    $parsedFiltered = parseTableData($filteredData);
    $parsedTotal = parseTableData($totalData);
    $processTimeIntervals = parseProcessTimeData($processTimeData);
    
    error_log("Parsed filtered orders: " . $parsedFiltered['orders']);
    error_log("Parsed total orders: " . $parsedTotal['orders']);
    error_log("Process time intervals: " . json_encode($processTimeIntervals));
    error_log("Process time HTML length: " . strlen($processTimeData));
    
    $result = [
        'orders' => [
            'value' => $parsedFiltered['orders'],
            'total' => $parsedTotal['orders'],
            'percentage' => calculatePercentage($parsedFiltered['orders'], $parsedTotal['orders'])
        ],
        'orderSum' => [
            'value' => $parsedFiltered['orderSum'],
            'total' => $parsedTotal['orderSum'],
            'percentage' => calculatePercentage($parsedFiltered['orderSum'], $parsedTotal['orderSum'])
        ],
        'marginProfit' => [
            'value' => $parsedFiltered['marginProfit'],
            'total' => $parsedTotal['marginProfit'],
            'percentage' => calculatePercentage($parsedFiltered['marginProfit'], $parsedTotal['marginProfit'])
        ],
        'allCalls' => [
            'value' => $parsedFiltered['allCalls'],
            'total' => $parsedTotal['allCalls'],
            'percentage' => calculatePercentage($parsedFiltered['allCalls'], $parsedTotal['allCalls'])
        ],
        'profileCalls' => [
            'value' => $parsedFiltered['profileCalls'],
            'total' => $parsedTotal['profileCalls'],
            'percentage' => calculatePercentage($parsedFiltered['profileCalls'], $parsedTotal['profileCalls'])
        ],
        'unprocessedCalls' => [
            'value' => $parsedFiltered['unprocessedCalls'],
            'total' => $parsedTotal['unprocessedCalls'],
            'percentage' => calculatePercentage($parsedFiltered['unprocessedCalls'], $parsedTotal['unprocessedCalls'])
        ],
        'missedCalls' => [
            'value' => $parsedFiltered['missedCalls'],
            'total' => $parsedTotal['missedCalls'],
            'percentage' => calculatePercentage($parsedFiltered['missedCalls'], $parsedTotal['missedCalls'])
        ],
        'missedNonTargetCalls' => [
            'value' => $parsedFiltered['missedNonTargetCalls'],
            'total' => $parsedTotal['missedNonTargetCalls'],
            'percentage' => calculatePercentage($parsedFiltered['missedNonTargetCalls'], $parsedTotal['missedNonTargetCalls'])
        ],
        'employees' => [
            'total' => [
                'value' => $parsedFiltered['employees']['total'],
                'totalValue' => $parsedTotal['employees']['total'],
                'percentage' => calculatePercentage($parsedFiltered['employees']['total'], $parsedTotal['employees']['total'])
            ],
            'work' => [
                'value' => $parsedFiltered['employees']['work'],
                'totalValue' => $parsedTotal['employees']['work'],
                'percentage' => calculatePercentage($parsedFiltered['employees']['work'], $parsedTotal['employees']['work'])
            ],
            'pause' => [
                'value' => $parsedFiltered['employees']['pause'],
                'totalValue' => $parsedTotal['employees']['pause'],
                'percentage' => calculatePercentage($parsedFiltered['employees']['pause'], $parsedTotal['employees']['pause'])
            ],
            'stop' => [
                'value' => $parsedFiltered['employees']['stop'],
                'totalValue' => $parsedTotal['employees']['stop'],
                'percentage' => calculatePercentage($parsedFiltered['employees']['stop'], $parsedTotal['employees']['stop'])
            ]
        ],
        'processTimeIntervals' => $processTimeIntervals
    ];
    
    echo json_encode($result);
    
} catch (Exception $e) {
    error_log("Error: " . $e->getMessage());
    http_response_code(500);
    echo json_encode([
        'error' => 'Failed to fetch data',
        'details' => $e->getMessage()
    ]);
}
?>
