<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Client-Info, Apikey');
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

require_once __DIR__ . '/config.php';
$config = $crm_credentials['mega'];

$debug = isset($_GET['debug']) && $_GET['debug'] === 'true';

error_log("=== MEGA API CALLED ===");
error_log("Using config: " . json_encode(['login' => $config['login'], 'roleId' => $config['roleId']]));

function loginToCRM($config) {
    $loginUrl   = 'https://datapoint.center/';
    $cookieFile = sys_get_temp_dir() . '/crm_cookies_' . uniqid() . '.txt';

    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL            => $loginUrl,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT        => 30,
        CURLOPT_COOKIEJAR      => $cookieFile,
        CURLOPT_COOKIEFILE     => $cookieFile,
        CURLOPT_HTTPHEADER     => [
            'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
        ],
    ]);
    curl_exec($ch);
    $initialCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    error_log("Initial request HTTP code: $initialCode");

    $postData = [
        'auth_login'     => $config['login'],
        'auth_password'  => $config['password'],
        'logok'          => 'Войти',
    ];

    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL            => $loginUrl,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => http_build_query($postData),
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT        => 30,
        CURLOPT_COOKIEJAR      => $cookieFile,
        CURLOPT_COOKIEFILE     => $cookieFile,
        CURLOPT_HEADER         => true,
        CURLOPT_HTTPHEADER     => [
            'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
            'Referer: ' . $loginUrl,
            'Origin: https://datapoint.center',
        ],
    ]);

    $response   = curl_exec($ch);
    $httpCode   = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $headerSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    $headers    = substr($response, 0, $headerSize);
    curl_close($ch);
    error_log("Login response HTTP code: $httpCode");

    $phpSessionId = '';
    if (preg_match('/Set-Cookie:.*?PHPSESSID=([^;]+)/i', $headers, $matches)) {
        $phpSessionId    = trim($matches[1]);
        $cookieContent   = "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n";
        $cookieContent  .= "datapoint.center\tFALSE\t/\tFALSE\t0\tPHPSESSID\t{$phpSessionId}\n";
        file_put_contents($cookieFile, $cookieContent);
        error_log("PHPSESSID found: $phpSessionId");
    }

    if ($httpCode === 302 || $httpCode === 303) {
        if (preg_match('/Location:\s*(.+)/i', $headers, $matches)) {
            $redirectUrl = trim($matches[1]);
            if (!preg_match('/^https?:\/\//', $redirectUrl)) {
                $redirectUrl = 'https://datapoint.center' . $redirectUrl;
            }
            $ch = curl_init();
            curl_setopt_array($ch, [
                CURLOPT_URL            => $redirectUrl,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_FOLLOWLOCATION => false,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_TIMEOUT        => 30,
                CURLOPT_COOKIEJAR      => $cookieFile,
                CURLOPT_COOKIEFILE     => $cookieFile,
            ]);
            curl_exec($ch);
            curl_close($ch);
        }
    }

    $sessionCookie = '';
    if (file_exists($cookieFile)) {
        $cookieContent = file_get_contents($cookieFile);
        if (preg_match('/PHPSESSID\s+([^\s\n]+)/', $cookieContent, $matches)) {
            $phpSessionId  = trim($matches[1]);
            $sessionCookie = 'PHPSESSID=' . $phpSessionId;
            error_log("PHPSESSID from file: $phpSessionId");
        }
    }

    if (empty($sessionCookie)) {
        error_log("ERROR: No PHPSESSID found");
        @unlink($cookieFile);
        return '';
    }

    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL            => 'https://datapoint.center/dashboard/',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => false,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_TIMEOUT        => 30,
        CURLOPT_COOKIEFILE     => $cookieFile,
        CURLOPT_HTTPHEADER     => [
            'Cookie: ' . $sessionCookie,
            'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        ],
    ]);
    $verifyResponse = curl_exec($ch);
    $verifyCode     = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    $isLoggedIn = strpos($verifyResponse, 'dashboard') !== false
               || strpos($verifyResponse, 'выход')    !== false
               || strpos($verifyResponse, 'auth_login') === false;

    error_log("Verification code: $verifyCode, Is logged in: " . ($isLoggedIn ? 'Yes' : 'No'));

    if (!$isLoggedIn) {
        error_log("ERROR: Login verification failed");
        @unlink($cookieFile);
        return '';
    }

    return $sessionCookie;
}

function fetchPage($url, $cookies, $cookieFile, $maxRetries = 3) {
    for ($attempt = 1; $attempt <= $maxRetries; $attempt++) {
        $ch = curl_init();
        curl_setopt_array($ch, [
            CURLOPT_URL            => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_TIMEOUT        => 30,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_COOKIEFILE     => $cookieFile,
            CURLOPT_COOKIEJAR      => $cookieFile,
            CURLOPT_HTTPHEADER     => [
                'Cookie: ' . $cookies,
                'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
                'Referer: https://datapoint.center/dashboard/',
            ],
        ]);
        $data     = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error    = curl_error($ch);
        curl_close($ch);

        if ($httpCode === 200 && !empty($data) && strlen($data) > 500) {
            error_log("fetchPage: success on attempt $attempt, length: " . strlen($data));
            return $data;
        }
        error_log("fetchPage attempt $attempt failed: HTTP $httpCode, error: $error");
        if ($attempt < $maxRetries) usleep(500000);
    }
    return false;
}

// Парсинг количества звонков из HTML
function parseCallsCount($html) {
    // Ищем «Кол-во звонков» / «Кол-во звонків» и число после
    if (preg_match('/Кол-во звонк[^<]*<\/td>\s*<td[^>]*>\s*(\d[\d\s]*)\s*<\/td>/ui', $html, $m)) {
        return (int) preg_replace('/\s/', '', $m[1]);
    }
    // Альтернативный вариант: число прямо в следующем td
    if (preg_match('/звонк[^<]{0,50}<\/td>\s*<td[^>]*>\s*(\d+)/ui', $html, $m)) {
        return (int) $m[1];
    }
    return 0;
}

// Парсинг таблицы заказов: Продукт, Количество, ФИО клиента
function parseOrdersTable($html) {
    $orders = [];

    // Находим ВСЕ таблицы и ищем ту, что содержит «Продукт» в заголовке
    if (!preg_match_all('/<table[^>]*>([\s\S]*?)<\/table>/i', $html, $allTables)) {
        error_log("parseOrdersTable: no tables found in HTML");
        return $orders;
    }

    $targetTableHtml = null;
    $productIdx  = -1;
    $quantityIdx = -1;
    $clientIdx   = -1;

    foreach ($allTables[0] as $tableHtml) {
        // Ищем заголовки (th или td в thead/первом tr)
        $headerHtml = '';
        if (preg_match('/<thead[^>]*>([\s\S]*?)<\/thead>/i', $tableHtml, $hm)) {
            $headerHtml = $hm[1];
        } elseif (preg_match('/<tr[^>]*>([\s\S]*?)<\/tr>/i', $tableHtml, $hm)) {
            $headerHtml = $hm[1];
        }

        $pIdx = -1; $qIdx = -1; $cIdx = -1;
        $cellPattern = '/<(?:th|td)[^>]*>([\s\S]*?)<\/(?:th|td)>/i';
        if (preg_match_all($cellPattern, $headerHtml, $cols)) {
            foreach ($cols[1] as $i => $colHtml) {
                $t = mb_strtolower(trim(strip_tags($colHtml)), 'UTF-8');
                if (strpos($t, 'продукт') !== false || strpos($t, 'product') !== false) {
                    $pIdx = $i;
                } elseif (strpos($t, 'кільк') !== false || strpos($t, 'колич') !== false || strpos($t, 'кол-во') !== false) {
                    $qIdx = $i;
                } elseif (strpos($t, 'фіо') !== false || strpos($t, 'фио') !== false || strpos($t, 'клієнт') !== false || strpos($t, 'клиент') !== false) {
                    $cIdx = $i;
                }
            }
        }

        // Нашли таблицу с колонкой «Продукт»
        if ($pIdx >= 0) {
            $targetTableHtml = $tableHtml;
            $productIdx  = $pIdx;
            $quantityIdx = $qIdx;
            $clientIdx   = $cIdx;
            error_log("parseOrdersTable: found target table, columns product=$productIdx quantity=$quantityIdx client=$clientIdx");
            break;
        }
    }

    if ($targetTableHtml === null) {
        error_log("parseOrdersTable: no table with 'Продукт' header found, trying fallback");
        // Фолбэк: берём самую большую таблицу
        usort($allTables[0], fn($a, $b) => strlen($b) - strlen($a));
        $targetTableHtml = $allTables[0][0];
    }

    // Парсим все строки tbody (или все tr, пропуская первую/заголовочную)
    $tbodyHtml = $targetTableHtml;
    if (preg_match('/<tbody[^>]*>([\s\S]*?)<\/tbody>/i', $targetTableHtml, $bm)) {
        $tbodyHtml = $bm[1];
    }

    if (!preg_match_all('/<tr([^>]*)>([\s\S]*?)<\/tr>/i', $tbodyHtml, $rows, PREG_SET_ORDER)) {
        error_log("parseOrdersTable: no rows found");
        return $orders;
    }

    $isFirstRow = ($productIdx < 0); // если не нашли заголовок — пропускаем первую строку
    foreach ($rows as $rowIdx => $row) {
        $trHtml = $row[2];

        // Пропускаем строку-заголовок если нет tbody
        if ($isFirstRow && $rowIdx === 0) continue;

        if (!preg_match_all('/<td[^>]*>([\s\S]*?)<\/td>/i', $trHtml, $cells)) continue;

        $cellTexts = array_map(function($c) {
            return trim(preg_replace('/\s+/', ' ', strip_tags($c)));
        }, $cells[1]);

        // Пропускаем строки с менее чем 2 ячейками (разделители, итоги)
        $nonEmpty = array_filter($cellTexts, fn($v) => $v !== '' && $v !== '&nbsp;');
        if (count($nonEmpty) < 2) continue;

        if ($productIdx >= 0) {
            $product  = isset($cellTexts[$productIdx])  ? $cellTexts[$productIdx]  : '';
            $quantity = $quantityIdx >= 0 && isset($cellTexts[$quantityIdx]) ? $cellTexts[$quantityIdx] : '';
            $client   = $clientIdx   >= 0 && isset($cellTexts[$clientIdx])   ? $cellTexts[$clientIdx]   : '';
        } else {
            // Фолбэк: первые три ячейки
            $product  = $cellTexts[0] ?? '';
            $quantity = $cellTexts[1] ?? '';
            $client   = $cellTexts[2] ?? '';
        }

        if (!empty($product) || !empty($client)) {
            $orders[] = [
                'product'    => $product,
                'quantity'   => $quantity,
                'clientName' => $client,
            ];
        }
    }

    error_log("parseOrdersTable: found " . count($orders) . " orders");
    return $orders;
}

try {
    $cookies = loginToCRM($config);
    if (empty($cookies)) {
        throw new Exception('Failed to authenticate');
    }
    error_log("Login successful, User: " . $config['login']);

    $cookieFile   = sys_get_temp_dir() . '/crm_cookies_mega_' . uniqid() . '.txt';
    $phpSessionId = str_replace('PHPSESSID=', '', $cookies);
    file_put_contents($cookieFile, "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n");
    file_put_contents($cookieFile, "datapoint.center\tFALSE\t/\tFALSE\t0\tPHPSESSID\t{$phpSessionId}\n", FILE_APPEND);

    $dataUrl = "https://datapoint.center/admin/report/desiner/72/view/"
        . "?filter_order_cdatetype=now"
        . "&filter_order_cdateperiod=mday"
        . "&filter_user_roleid%5B%5D=" . urlencode($config['roleId'])
        . "&filter_user_manageronline=online"
        . "&filter_event_uservoip_que_source%5B%5D=" . urlencode($config['sourceFilter'])
        . "&templateid=&ok=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C&page=0";

    error_log("Data URL: $dataUrl");

    $html = fetchPage($dataUrl, $cookies, $cookieFile);

    @unlink($cookieFile);

    if ($debug) {
        echo json_encode([
            'html'    => substr((string) $html, 0, 8000),
            'cookies' => $cookies,
            'config'  => ['login' => $config['login'], 'roleId' => $config['roleId'], 'source' => $config['sourceFilter']],
        ]);
        exit;
    }

    if (!$html) {
        throw new Exception('Failed to fetch data from CRM');
    }

    $calls  = parseCallsCount($html);
    $orders = parseOrdersTable($html);

    error_log("Calls: $calls, Orders: " . count($orders));

    echo json_encode([
        'calls'  => $calls,
        'orders' => $orders,
    ]);

} catch (Exception $e) {
    error_log("MEGA Error: " . $e->getMessage());
    http_response_code(500);
    echo json_encode([
        'error'   => 'Failed to fetch data',
        'details' => $e->getMessage(),
    ]);
}
?>
